### ISSUE TITLE
Unimplemented instruction: OpAtomicExchange 

### ISSUE THREAD

**Issue by kpet** [talvos/talvos#3]
This is one of the issues I've run into trying to run the OpenCL conformance tests via clvk. I can provide a SPIR-V module if that's useful.

**Comment by jrprice** [comment]
The only one of the atomics tests in the OpenCL CTS that I could run was `atomic_add_index`, since clspv doesn't seem to like any of the others. Talvos does now pass all of the tests in the Vulkan CTS that have `atomic` in the name (excluding images), so I think this should work now. Let me know if you have any issues.

**Comment by kpet** [comment]
Thanks! I discovered the lack of support with a modified clspv that does a bit more with atomics. I'll retest.
